"""Verify one E1 Protocol B1 RoboGuide run against the B1 acceptance gates.

F07: provenance is verified through the single canonical implementation
(``roboguide_eval.b1_provenance.verify_b1_provenance``); weak substring and
structural-equality heuristics are removed. The b1-provenance.json artifact
generated by the run script is mandatory.
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).parent.parent.parent.parent
STATIC_PLAN = Path(__file__).parent / "mission-plan.json"


def _load(path: Path) -> dict[str, Any] | None:
    """Load one JSON file or return None when absent/malformed."""
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return document if isinstance(document, dict) else None


def _plan_intents(plan: dict[str, Any]) -> list[tuple[str, dict[str, Any]]]:
    """Extract (destination, objective) intent pairs from one MissionPlan doc."""
    intents: list[tuple[str, dict[str, Any]]] = []
    for task in plan.get("tasks", []):
        for role in task.get("roles", []):
            intent = role.get("execution_intent", {})
            destination = (intent.get("parameters") or {}).get("destination")
            intents.append((destination if isinstance(destination, str) else "", intent))
    return intents


def _load_provenance_record(run: Path) -> dict[str, Any] | None:
    """Load the b1-provenance.json artifact (mandatory for B1 runs)."""
    return _load(run / "b1-provenance.json")


def verify(run: Path) -> dict[str, Any]:
    """Evaluate the B1 acceptance gates from persisted run evidence.

    Provenance is delegated to the canonical ``verify_b1_provenance``
    implementation, which enforces mandatory record presence, digest-chain
    integrity, Controller identity match, and anti-forgery gates.
    """
    # Late import so the scenario script stays runnable without the evaluation
    # package when only structural checks are needed.
    sys.path.insert(0, str(REPO_ROOT / "evaluation" / "src"))
    from roboguide_eval.b1_provenance import (
        ProvenanceFailure,
    )
    from roboguide_eval.b1_provenance import (
        verify_b1_provenance as _verify_chain,
    )

    request = _load(run / "b1-request-record.json")
    mission = _load(run / "mission.json")
    shared = _load(run / "evidence/shared-world-summary.json")
    static_plan = _load(STATIC_PLAN)
    instruction = ""
    b1_input = _load(Path(__file__).parent / "b1-input.json")
    if b1_input:
        instruction = str(b1_input.get("instruction", ""))

    lifecycle = str(request.get("lifecycle")) if request else "missing"
    dialogue = json.dumps(request.get("dialogue", []), ensure_ascii=False) if request else ""
    mi_ran = bool(request and request.get("plan"))
    instruction_reached_mi = bool(instruction.strip()) and instruction.strip()[:80] in dialogue

    def _sha(text: str) -> str:
        """Hash one text for evidence."""
        return hashlib.sha256(text.encode("utf-8")).hexdigest()

    plan = (request or {}).get("plan") or {}
    plan_digest = (
        _sha(json.dumps(plan, sort_keys=True, ensure_ascii=False, separators=(",", ":")))
        if plan
        else None
    )
    static_digest = (
        _sha(json.dumps(static_plan, sort_keys=True, ensure_ascii=False, separators=(",", ":")))
        if static_plan
        else None
    )

    intents = _plan_intents(plan) if plan else []
    destinations = sorted({d for d, _ in intents})

    # --- F-06 tri-state benchmark authority ---
    benchmark_tri_state = "BENCHMARK_UNAVAILABLE"
    benchmark_reason = "authority_document_missing_or_malformed"
    shared = _load(run / "evidence/shared-world-summary.json")
    if shared:
        pddl = shared.get("official_pddl_success")
        if isinstance(pddl, bool):
            benchmark_tri_state = "BENCHMARK_TRUE" if pddl else "BENCHMARK_FALSE"
            benchmark_reason = "official_pddl_success_authoritative"
        else:
            benchmark_reason = "official_pddl_success_missing_or_not_bool"

    # --- F-07 canonical provenance verification ---
    provenance_record = _load_provenance_record(run)
    controller_mission_id = (mission or {}).get("mission_id") if mission else None
    controller_group_id = (mission or {}).get("group_id") if mission else None
    attempts = _load(run / "execution-attempts.json") or {}
    observed_execution_ids = tuple(
        str(a["execution_id"])
        for a in attempts.get("attempts", [])
        if isinstance(a, dict) and a.get("execution_id")
    )
    # genuine_mi_invocation: the scenario script observes the Mission Service
    # accepting the POST (lifecycle reaches Accepted) — this is the
    # runtime-observed MI invocation evidence.
    genuine_mi_invocation = lifecycle == "Accepted"

    provenance = _verify_chain(
        record=provenance_record,
        frozen_input=b1_input,
        request_record=request,
        controller_mission_id=controller_mission_id,
        controller_plan=mission,
        benchmark_evidence=shared,
        static_b2_plan=static_plan,
        controller_group_id=controller_group_id,
        observed_execution_ids=observed_execution_ids,
        genuine_mi_invocation=genuine_mi_invocation,
    )
    provenance_failures = [f.value for f in provenance.failures]
    provenance_passed = provenance.passed

    # --- semantic intent gates (unchanged) ---
    destinations = sorted({d for d, _ in [(dest, intent) for dest, intent in intents]})
    goals_covered = destinations == ["TARGET_any_targets|0", "any_targets|0"]
    events = _load(run / "events.json") or {}
    events_text = json.dumps(events, ensure_ascii=False)
    intent_execution_consistent = bool(destinations) and all(
        destination in events_text for destination in destinations
    )

    valid_run = "VALID_RUN" if provenance_passed else "INVALID_INFRA"
    valid_for_formal_population = provenance_passed

    checks = {
        "same_high_level_task": instruction_reached_mi,
        "mission_intelligence_ran": mi_ran,
        "static_plan_fallback_absent": ProvenanceFailure.STATIC_B2_PLAN_EQUALITY
        not in provenance.failures,
        "full_semantic_goals_covered": goals_covered,
        "mission_terminal_or_mi_terminal": (
            (mission or {}).get("status") in {"Completed", "Failed", "Cancelled"}
            or lifecycle in {"Blocked", "Failed", "NeedsClarification"}
        ),
        "provenance_chain_passed": provenance_passed,
        "intent_execution_consistent": intent_execution_consistent,
        "valid_for_formal_population": valid_for_formal_population,
    }
    outcomes = (shared or {}).get("outcomes", {})
    context = {
        "lifecycle": lifecycle,
        "mission_status": (mission or {}).get("status"),
        "plan_destinations": destinations,
        "plan_tasks": [task.get("id") for task in plan.get("tasks", [])] if plan else [],
        "official_pddl_success": bool((shared or {}).get("official_pddl_success", False)),
        "per_agent_states": {agent: outcome.get("state") for agent, outcome in outcomes.items()},
        "instruction_sha256": _sha(instruction) if instruction else None,
        "accepted_plan_canonical_digest": plan_digest,
        "static_b2_plan_canonical_digest": static_digest,
        "benchmark_tri_state": benchmark_tri_state,
        "benchmark_outcome_reason": benchmark_reason,
        "provenance_failures": provenance_failures,
        "run_validity": valid_run,
        "provenance_schema": "roboguide.e1.b1-provenance/v0.1",
        "stage2_context_diff": {
            "roboguide_assignment_texts": [intent.get("objective") for _, intent in intents],
            "roboguide_assignment_sha256": _sha(
                json.dumps(
                    [intent.get("objective") for _, intent in intents],
                    ensure_ascii=False,
                )
            )
            if intents
            else None,
            "scene_context": "shared scene_description.txt retained in evidence/",
        },
        "population_admission": {
            "valid_for_formal_population": valid_for_formal_population,
            "benchmark_tri_state": benchmark_tri_state,
            "run_validity": valid_run,
            "invalid_reasons": provenance_failures,
        },
    }
    passed = all(bool(value) for value in checks.values())
    return {
        "schema": "roboguide.e1-b1-verdict/v0.1",
        "run": run.name,
        "checks": checks,
        "context": context,
        "verdict": "PASS" if passed else "FAIL",
    }


def main() -> None:
    """Print one machine-readable B1 verdict."""
    if len(sys.argv) != 2:
        raise SystemExit("usage: verify-b1.py RUN_DIRECTORY")
    print(json.dumps(verify(Path(sys.argv[1])), indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
