//! Runtime lifecycle for transport-neutral execution coordination mechanisms.

use crate::{ExecutionRuntimeError, RuntimeExecutionManager};
use domain::{
    ContextRoleId, CoordinationContext, CoordinationContextId, CoordinationMechanism,
    ExecutionCouplingMode, ExecutionGroupId, GroupSharedViewSpec, LocalSystemId, NodeId,
    PeerChannelSpec, TimestampMs,
};
use std::collections::{BTreeMap, BTreeSet};

/// Stable Runtime key for one Context inside one Mission-level Group.
pub(crate) type CoordinationKey = (ExecutionGroupId, CoordinationContextId);

/// Observable lifecycle of a deployment-resolved peer coordination channel.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum PeerChannelLifecycle {
    /// Descriptor is registered but Local EAIOS peers have not confirmed readiness.
    Planned,
    /// Local EAIOS peers confirmed the direct channel is ready.
    Ready,
    /// Runtime fenced channel use after ambiguity or peer loss.
    Fenced,
    /// Coordination context ended and the descriptor is no longer usable.
    Closed,
}

/// Runtime-owned descriptor and lifecycle for a direct Local EAIOS peer channel.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct RuntimePeerChannel {
    /// Mission-level Group containing the peers.
    group_id: ExecutionGroupId,
    /// Coordination Context declaring the channel.
    context_id: CoordinationContextId,
    /// Logical ContextRole peers independent of Node placement.
    peers: Vec<ContextRoleId>,
    /// Deployment-resolved transport-neutral profile.
    descriptor: PeerChannelSpec,
    /// Current channel lifecycle.
    pub(crate) lifecycle: PeerChannelLifecycle,
    /// Latest identified Local EAIOS acknowledgement from each logical peer endpoint.
    #[serde(default)]
    pub(crate) readiness: Vec<PeerChannelReadinessEvidence>,
}

/// Identified readiness evidence for one logical peer-channel endpoint.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct PeerChannelReadinessEvidence {
    /// Group containing the coordination Context.
    pub group_id: ExecutionGroupId,
    /// Coordination Context declaring the channel.
    pub context_id: CoordinationContextId,
    /// Logical ContextRole acknowledged by the Local EAIOS.
    pub context_role_id: ContextRoleId,
    /// Current Node session that supplied the acknowledgement.
    pub node_id: NodeId,
    /// Registered node-local EAIOS that established this endpoint.
    pub local_system_id: LocalSystemId,
    /// Session identity issued by the current Node protocol route.
    pub session_id: String,
    /// Shared instance identity generated by the Local EAIOS channel establishment.
    pub channel_instance_id: String,
    /// Descriptor profile confirmed by the Local EAIOS.
    pub profile_id: String,
    /// Descriptor message schema confirmed by the Local EAIOS.
    pub message_schema: String,
    /// Node-management sequence of the acknowledgement.
    pub sequence: u64,
    /// RoboGuide-local receive time.
    pub received_at: TimestampMs,
    /// RoboGuide-local deadline after which this acknowledgement cannot authorize readiness.
    pub expires_at: TimestampMs,
    /// Whether this endpoint currently confirms readiness.
    pub ready: bool,
}

impl RuntimePeerChannel {
    /// Returns the owning Mission-level Group.
    pub const fn group_id(&self) -> &ExecutionGroupId {
        &self.group_id
    }

    /// Returns the declaring coordination Context.
    pub const fn context_id(&self) -> &CoordinationContextId {
        &self.context_id
    }

    /// Returns logical peers without resolving them to physical Nodes.
    pub fn peers(&self) -> &[ContextRoleId] {
        &self.peers
    }

    /// Returns the deployment-resolved channel descriptor.
    pub const fn descriptor(&self) -> &PeerChannelSpec {
        &self.descriptor
    }

    /// Returns the current Runtime lifecycle.
    pub const fn lifecycle(&self) -> PeerChannelLifecycle {
        self.lifecycle
    }

    /// Returns the latest endpoint acknowledgements retained for this channel.
    pub fn readiness(&self) -> &[PeerChannelReadinessEvidence] {
        &self.readiness
    }
}

/// Runtime copy of one Mission-owned coordination declaration.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub(crate) struct RuntimeCoordinationContext {
    /// Owning Mission-level Group.
    pub(crate) group_id: ExecutionGroupId,
    /// Mission-owned Context identity.
    pub(crate) context_id: CoordinationContextId,
    /// Context default coupling mode.
    pub(crate) coupling_mode: ExecutionCouplingMode,
    /// Selective shared view declaration, when present.
    pub(crate) shared_view: Option<GroupSharedViewSpec>,
    /// Number of Mission-owned relation specifications in this Context.
    #[serde(default)]
    pub(crate) relation_count: usize,
}

/// Readiness of the mechanisms declared by a coupling mode.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CoordinationReadiness {
    /// All mode-required mechanisms are declared and live.
    Ready,
    /// The mode requires a selective Group shared view which is absent.
    WaitingForSharedView,
    /// The mode requires a direct peer channel which is absent or not ready.
    WaitingForPeerChannel,
    /// The mode requires at least one Runtime relation evidence stream.
    WaitingForRelationEvidence,
}

impl RuntimeExecutionManager {
    /// Registers one Mission-owned Context without resolving peers to physical Nodes.
    pub fn register_coordination_context(
        &mut self,
        group_id: &ExecutionGroupId,
        context: &CoordinationContext,
    ) -> Result<(), ExecutionRuntimeError> {
        let key = (group_id.clone(), context.context_id().clone());
        let declaration = RuntimeCoordinationContext {
            group_id: group_id.clone(),
            context_id: context.context_id().clone(),
            coupling_mode: context.coupling_mode(),
            shared_view: context.shared_view().cloned(),
            relation_count: context.relations().len(),
        };
        let channel = context.peer_channel().map(|descriptor| {
            let mut peers = context
                .roles()
                .iter()
                .map(|role| role.context_role_id().clone())
                .collect::<Vec<_>>();
            peers.sort();
            RuntimePeerChannel {
                group_id: group_id.clone(),
                context_id: context.context_id().clone(),
                peers,
                descriptor: descriptor.clone(),
                lifecycle: PeerChannelLifecycle::Planned,
                readiness: Vec::new(),
            }
        });
        if let Some(existing) = self.coordination_contexts.get(&key) {
            if existing != &declaration {
                return Err(ExecutionRuntimeError::ExecutionConflict(format!(
                    "coordination Context {} in Group {}",
                    context.context_id(),
                    group_id
                )));
            }
            let channel_matches = match (self.peer_channels.get(&key), channel.as_ref()) {
                (None, None) => true,
                (Some(existing), Some(expected)) => {
                    existing.descriptor == expected.descriptor && existing.peers == expected.peers
                }
                _ => false,
            };
            if !channel_matches {
                return Err(ExecutionRuntimeError::ExecutionConflict(format!(
                    "peer channel {} in Group {}",
                    context.context_id(),
                    group_id
                )));
            }
            return Ok(());
        }
        if self.peer_channels.contains_key(&key) {
            return Err(ExecutionRuntimeError::ExecutionConflict(format!(
                "orphan peer channel {} in Group {}",
                context.context_id(),
                group_id
            )));
        }
        self.coordination_contexts.insert(key.clone(), declaration);
        if let Some(channel) = channel {
            self.peer_channels.insert(key, channel);
        }
        Ok(())
    }

    /// Confirms restored coordination declarations match an accepted MissionPlan exactly.
    pub fn validate_coordination_contexts(
        &self,
        group_id: &ExecutionGroupId,
        contexts: &[CoordinationContext],
    ) -> Result<(), ExecutionRuntimeError> {
        let mut expected_contexts = BTreeMap::new();
        let mut expected_channels = BTreeMap::new();
        for context in contexts {
            let key = (group_id.clone(), context.context_id().clone());
            expected_contexts.insert(
                key.clone(),
                RuntimeCoordinationContext {
                    group_id: group_id.clone(),
                    context_id: context.context_id().clone(),
                    coupling_mode: context.coupling_mode(),
                    shared_view: context.shared_view().cloned(),
                    relation_count: context.relations().len(),
                },
            );
            if let Some(descriptor) = context.peer_channel() {
                let mut peers = context
                    .roles()
                    .iter()
                    .map(|role| role.context_role_id().clone())
                    .collect::<Vec<_>>();
                peers.sort();
                expected_channels.insert(key, (peers, descriptor.clone()));
            }
        }
        let actual_contexts = self
            .coordination_contexts
            .iter()
            .filter(|((candidate, _), _)| candidate == group_id)
            .map(|(key, value)| (key.clone(), value.clone()))
            .collect::<BTreeMap<_, _>>();
        let actual_channels = self
            .peer_channels
            .iter()
            .filter(|((candidate, _), _)| candidate == group_id)
            .map(|(key, value)| (key.clone(), (value.peers.clone(), value.descriptor.clone())))
            .collect::<BTreeMap<_, _>>();
        let legacy_default_contexts = actual_contexts.is_empty()
            && expected_contexts.values().all(|context| {
                context.coupling_mode == ExecutionCouplingMode::Independent
                    && context.shared_view.is_none()
            })
            && expected_channels.is_empty();
        if !legacy_default_contexts
            && (expected_contexts != actual_contexts || expected_channels != actual_channels)
        {
            return Err(ExecutionRuntimeError::InvalidCheckpoint(format!(
                "Runtime coordination declarations differ for Group {group_id}"
            )));
        }
        Ok(())
    }

    /// Returns mode mechanism readiness without applying Task progression policy.
    pub fn coordination_readiness(
        &self,
        group_id: &ExecutionGroupId,
        context_id: &CoordinationContextId,
    ) -> Option<CoordinationReadiness> {
        let key = (group_id.clone(), context_id.clone());
        let mode = self.coordination_contexts.get(&key)?.coupling_mode;
        self.coordination_readiness_for_mode(group_id, context_id, mode)
    }

    /// Returns mechanism readiness for a Task's effective mode override.
    pub fn coordination_readiness_for_mode(
        &self,
        group_id: &ExecutionGroupId,
        context_id: &CoordinationContextId,
        mode: ExecutionCouplingMode,
    ) -> Option<CoordinationReadiness> {
        let key = (group_id.clone(), context_id.clone());
        let context = self.coordination_contexts.get(&key)?;
        // Sequential handoff readiness is supplied by the existing Mission DAG and Task
        // lifecycle; Runtime owns no duplicate handoff registry in this first version.
        if mode.requires(CoordinationMechanism::GroupSharedState) && context.shared_view.is_none() {
            return Some(CoordinationReadiness::WaitingForSharedView);
        }
        if mode.requires(CoordinationMechanism::RelationEvidence) && context.relation_count == 0 {
            return Some(CoordinationReadiness::WaitingForRelationEvidence);
        }
        if mode.requires(CoordinationMechanism::DirectPeerChannel)
            && self
                .peer_channels
                .get(&key)
                .is_none_or(|channel| channel.lifecycle != PeerChannelLifecycle::Ready)
        {
            return Some(CoordinationReadiness::WaitingForPeerChannel);
        }
        Some(CoordinationReadiness::Ready)
    }

    /// Records one identified Local EAIOS endpoint acknowledgement and derives channel readiness.
    pub fn observe_peer_channel_readiness(
        &mut self,
        evidence: PeerChannelReadinessEvidence,
    ) -> Result<(), ExecutionRuntimeError> {
        self.refresh_peer_channel_deadlines(evidence.received_at);
        if evidence.expires_at <= evidence.received_at {
            return Err(ExecutionRuntimeError::ReconciliationRequired(
                "peer readiness expiry must follow its receive time".to_string(),
            ));
        }
        let key = (evidence.group_id.clone(), evidence.context_id.clone());
        let channel = self.peer_channels.get_mut(&key).ok_or_else(|| {
            ExecutionRuntimeError::ReconciliationRequired(format!(
                "unknown peer channel {} in Group {}",
                evidence.context_id, evidence.group_id
            ))
        })?;
        if channel.lifecycle == PeerChannelLifecycle::Closed {
            return Err(ExecutionRuntimeError::ReconciliationRequired(
                "closed peer channel cannot accept readiness evidence".to_string(),
            ));
        }
        if !channel.peers.contains(&evidence.context_role_id) {
            return Err(ExecutionRuntimeError::ReconciliationRequired(
                "peer readiness references an undeclared ContextRole".to_string(),
            ));
        }
        if channel.descriptor.profile_id != evidence.profile_id
            || channel.descriptor.message_schema != evidence.message_schema
        {
            channel
                .readiness
                .retain(|ack| ack.context_role_id != evidence.context_role_id);
            channel.lifecycle = PeerChannelLifecycle::Fenced;
            return Ok(());
        }
        if let Some(existing) = channel
            .readiness
            .iter()
            .find(|ack| ack.context_role_id == evidence.context_role_id)
            && evidence.session_id == existing.session_id
        {
            if evidence.sequence < existing.sequence {
                return Err(ExecutionRuntimeError::ReconciliationRequired(
                    "older peer readiness acknowledgement cannot replace current evidence"
                        .to_string(),
                ));
            }
            if evidence.sequence == existing.sequence {
                if existing == &evidence {
                    return Ok(());
                }
                channel
                    .readiness
                    .retain(|ack| ack.context_role_id != evidence.context_role_id);
                channel.lifecycle = PeerChannelLifecycle::Fenced;
                return Ok(());
            }
        }
        channel
            .readiness
            .retain(|ack| ack.context_role_id != evidence.context_role_id);
        let ready = evidence.ready;
        let observed_at = evidence.received_at;
        channel.readiness.push(evidence);
        channel
            .readiness
            .sort_by(|left, right| left.context_role_id.cmp(&right.context_role_id));
        if !ready {
            channel.lifecycle = PeerChannelLifecycle::Fenced;
            return Ok(());
        }
        let instances = channel
            .readiness
            .iter()
            .filter(|ack| ack.ready)
            .map(|ack| ack.channel_instance_id.as_str())
            .collect::<BTreeSet<_>>();
        let all_ready = channel.peers.iter().all(|peer| {
            channel.readiness.iter().any(|ack| {
                &ack.context_role_id == peer && ack.ready && ack.expires_at > observed_at
            })
        });
        channel.lifecycle = if all_ready && instances.len() == 1 {
            PeerChannelLifecycle::Ready
        } else if instances.len() > 1 || channel.lifecycle == PeerChannelLifecycle::Fenced {
            PeerChannelLifecycle::Fenced
        } else {
            PeerChannelLifecycle::Planned
        };
        Ok(())
    }

    /// Fences channels whose receive-relative Local EAIOS readiness evidence has expired.
    pub fn refresh_peer_channel_deadlines(&mut self, now: TimestampMs) {
        for channel in self.peer_channels.values_mut() {
            if channel.lifecycle != PeerChannelLifecycle::Closed
                && channel
                    .readiness
                    .iter()
                    .any(|ack| ack.ready && ack.expires_at <= now)
            {
                channel.lifecycle = PeerChannelLifecycle::Fenced;
            }
        }
    }

    /// Invalidates every endpoint reported by a disconnected Node and fences its channels.
    ///
    /// Removal prevents an unrelated peer renewal from reusing a positive acknowledgement from
    /// the lost route. The disconnected Local EAIOS must provide fresh evidence in a new session.
    pub fn fence_peer_channels_for_node(&mut self, node_id: &NodeId) {
        for channel in self.peer_channels.values_mut() {
            if channel.readiness.iter().any(|ack| &ack.node_id == node_id) {
                channel.lifecycle = PeerChannelLifecycle::Fenced;
                channel.readiness.retain(|ack| &ack.node_id != node_id);
            }
        }
    }

    /// Fences a direct peer channel while preserving its declaration for reconciliation.
    pub fn fence_peer_channel(
        &mut self,
        group_id: &ExecutionGroupId,
        context_id: &CoordinationContextId,
    ) -> Result<(), ExecutionRuntimeError> {
        self.set_peer_channel_lifecycle(group_id, context_id, PeerChannelLifecycle::Fenced)
    }

    /// Closes a direct peer channel descriptor after its coordination scope ends.
    pub fn close_peer_channel(
        &mut self,
        group_id: &ExecutionGroupId,
        context_id: &CoordinationContextId,
    ) -> Result<(), ExecutionRuntimeError> {
        self.set_peer_channel_lifecycle(group_id, context_id, PeerChannelLifecycle::Closed)
    }

    /// Closes every direct peer descriptor when its Mission-level Group leaves execution.
    pub fn close_peer_channels_for_group(&mut self, group_id: &ExecutionGroupId) {
        for ((candidate, _), channel) in &mut self.peer_channels {
            if candidate == group_id {
                channel.lifecycle = PeerChannelLifecycle::Closed;
                channel.readiness.clear();
            }
        }
    }

    /// Returns peer channel snapshots for one Group in stable Context order.
    pub fn peer_channels(&self, group_id: &ExecutionGroupId) -> Vec<RuntimePeerChannel> {
        self.peer_channels
            .values()
            .filter(|channel| channel.group_id() == group_id)
            .cloned()
            .collect()
    }

    /// Returns peer channel snapshots with receive-relative expiry reflected without mutation.
    pub fn peer_channels_at(
        &self,
        group_id: &ExecutionGroupId,
        now: TimestampMs,
    ) -> Vec<RuntimePeerChannel> {
        self.peer_channels(group_id)
            .into_iter()
            .map(|mut channel| {
                if channel.lifecycle != PeerChannelLifecycle::Closed
                    && channel
                        .readiness
                        .iter()
                        .any(|ack| ack.ready && ack.expires_at <= now)
                {
                    channel.lifecycle = PeerChannelLifecycle::Fenced;
                }
                channel
            })
            .collect()
    }

    /// Changes one known channel lifecycle without creating transport authority.
    fn set_peer_channel_lifecycle(
        &mut self,
        group_id: &ExecutionGroupId,
        context_id: &CoordinationContextId,
        lifecycle: PeerChannelLifecycle,
    ) -> Result<(), ExecutionRuntimeError> {
        let channel = self
            .peer_channels
            .get_mut(&(group_id.clone(), context_id.clone()))
            .ok_or_else(|| {
                ExecutionRuntimeError::ReconciliationRequired(format!(
                    "unknown peer channel {context_id} in Group {group_id}"
                ))
            })?;
        if channel.lifecycle == PeerChannelLifecycle::Closed
            && lifecycle != PeerChannelLifecycle::Closed
        {
            return Err(ExecutionRuntimeError::ReconciliationRequired(format!(
                "closed peer channel {context_id} in Group {group_id} cannot be reopened"
            )));
        }
        channel.lifecycle = lifecycle;
        Ok(())
    }
}

/// Restores coordination maps while rejecting duplicate and orphan channels.
#[allow(clippy::type_complexity)]
pub(crate) fn restore_coordination_maps(
    contexts: Vec<RuntimeCoordinationContext>,
    channels: Vec<RuntimePeerChannel>,
) -> Result<
    (
        BTreeMap<CoordinationKey, RuntimeCoordinationContext>,
        BTreeMap<CoordinationKey, RuntimePeerChannel>,
    ),
    ExecutionRuntimeError,
> {
    let mut context_map = BTreeMap::new();
    for context in contexts {
        if let Some(view) = &context.shared_view {
            view.validate().map_err(|error| {
                ExecutionRuntimeError::InvalidCheckpoint(format!(
                    "checkpoint Group shared view is invalid: {error}"
                ))
            })?;
        }
        let key = (context.group_id.clone(), context.context_id.clone());
        if context_map.insert(key, context).is_some() {
            return Err(ExecutionRuntimeError::InvalidCheckpoint(
                "checkpoint contains duplicate coordination Context".to_string(),
            ));
        }
    }
    let mut channel_map = BTreeMap::new();
    for channel in channels {
        let key = (channel.group_id.clone(), channel.context_id.clone());
        let readiness_roles = channel
            .readiness
            .iter()
            .map(|evidence| &evidence.context_role_id)
            .collect::<BTreeSet<_>>();
        let readiness_valid = readiness_roles.len() == channel.readiness.len()
            && channel.readiness.iter().all(|evidence| {
                evidence.group_id == channel.group_id
                    && evidence.context_id == channel.context_id
                    && channel.peers.contains(&evidence.context_role_id)
                    && evidence.profile_id == channel.descriptor.profile_id
                    && evidence.message_schema == channel.descriptor.message_schema
                    && !evidence.node_id.as_str().trim().is_empty()
                    && !evidence.local_system_id.as_str().trim().is_empty()
                    && !evidence.session_id.trim().is_empty()
                    && !evidence.channel_instance_id.trim().is_empty()
                    && evidence.sequence > 0
                    && evidence.expires_at > evidence.received_at
            });
        if !context_map.contains_key(&key)
            || channel.peers.len() < 2
            || channel.peers.iter().collect::<BTreeSet<_>>().len() != channel.peers.len()
            || channel.descriptor.profile_id.trim().is_empty()
            || channel.descriptor.message_schema.trim().is_empty()
            || !readiness_valid
            || channel_map.insert(key, channel).is_some()
        {
            return Err(ExecutionRuntimeError::InvalidCheckpoint(
                "checkpoint contains duplicate or orphan peer channel".to_string(),
            ));
        }
    }
    Ok((context_map, channel_map))
}

#[cfg(test)]
mod tests {
    use super::*;
    use domain::{ActorId, ContextRole, ExecutionRelationSpec};

    /// Sequential handoff delegates readiness to the Mission DAG instead of a Runtime registry.
    #[test]
    fn sequential_handoff_uses_existing_task_progression() {
        let context_id = CoordinationContextId::new("handoff").expect("context id valid");
        let context = CoordinationContext::new_with_coordination(
            context_id.clone(),
            vec![ContextRole::new(
                ContextRoleId::new("carrier").expect("role id valid"),
                ActorId::new("carrier").expect("actor id valid"),
            )],
            Vec::new(),
            ExecutionCouplingMode::SequentialHandoff,
            None,
            None,
        )
        .expect("context valid");
        let group_id = ExecutionGroupId::new("group-handoff").expect("group id valid");
        let mut runtime = RuntimeExecutionManager::new();
        runtime
            .register_coordination_context(&group_id, &context)
            .expect("context registers");

        assert_eq!(
            runtime.coordination_readiness(&group_id, &context_id),
            Some(CoordinationReadiness::Ready)
        );
    }

    /// A tightly coupled Context keeps a planned channel until local readiness is confirmed.
    #[test]
    fn peer_channel_lifecycle_is_explicit_and_checkpointed() {
        let context_id = CoordinationContextId::new("guidance").expect("context id valid");
        let context = CoordinationContext::new_with_coordination(
            context_id.clone(),
            vec![
                ContextRole::new(
                    ContextRoleId::new("dog").expect("role id valid"),
                    ActorId::new("dog").expect("actor id valid"),
                ),
                ContextRole::new(
                    ContextRoleId::new("cane").expect("role id valid"),
                    ActorId::new("cane").expect("actor id valid"),
                ),
            ],
            vec![
                ExecutionRelationSpec::new(
                    domain::ExecutionRelationId::new("dog-guards-cane").expect("relation id valid"),
                    domain::PlannedExecutionRef::new(
                        domain::TaskId::new("dog-task").expect("task id valid"),
                        domain::RoleId::new("dog-role").expect("role id valid"),
                    ),
                    domain::PlannedExecutionRef::new(
                        domain::TaskId::new("cane-task").expect("task id valid"),
                        domain::RoleId::new("cane-role").expect("role id valid"),
                    ),
                    domain::ExecutionRelationKind::RequiresActive,
                )
                .expect("relation valid"),
            ],
            ExecutionCouplingMode::TightlyCoupledCooperation,
            Some(
                GroupSharedViewSpec::new(
                    None,
                    vec![
                        domain::GroupViewBinding::new(
                            ContextRoleId::new("dog").expect("context role id valid"),
                            domain::GroupViewField::Pose,
                            "dog-pose",
                            "roboguide.pose/v1",
                        )
                        .expect("view binding valid"),
                    ],
                    true,
                )
                .expect("shared view valid"),
            ),
            Some(PeerChannelSpec {
                profile_id: "guidance-peer".to_string(),
                message_schema: "guidance/v1".to_string(),
            }),
        )
        .expect("context valid");
        let group_id = ExecutionGroupId::new("group-guidance").expect("group id valid");
        let mut runtime = RuntimeExecutionManager::new();
        runtime
            .register_coordination_context(&group_id, &context)
            .expect("context registers");
        let conflicting_context = CoordinationContext::new_with_coordination(
            context_id.clone(),
            context.roles().to_vec(),
            context.relations().to_vec(),
            ExecutionCouplingMode::TightlyCoupledCooperation,
            context.shared_view().cloned(),
            Some(PeerChannelSpec {
                profile_id: "different-peer".to_string(),
                message_schema: "guidance/v1".to_string(),
            }),
        )
        .expect("conflicting context remains structurally valid");
        assert!(
            runtime
                .register_coordination_context(&group_id, &conflicting_context)
                .is_err()
        );
        assert_eq!(
            runtime.peer_channels(&group_id)[0].descriptor().profile_id,
            "guidance-peer"
        );
        assert_eq!(
            runtime.coordination_readiness(&group_id, &context_id),
            Some(CoordinationReadiness::WaitingForPeerChannel)
        );
        runtime
            .peer_channels
            .get_mut(&(group_id.clone(), context_id.clone()))
            .expect("registered channel remains present")
            .lifecycle = PeerChannelLifecycle::Ready;
        assert_eq!(
            runtime.coordination_readiness(&group_id, &context_id),
            Some(CoordinationReadiness::Ready)
        );
        let restored = RuntimeExecutionManager::restore(runtime.checkpoint())
            .expect("checkpoint restores conservatively");
        assert_eq!(
            restored.peer_channels(&group_id)[0].lifecycle(),
            PeerChannelLifecycle::Fenced
        );
        let mut restored = restored;
        restored.close_peer_channels_for_group(&group_id);
        assert_eq!(
            restored.peer_channels(&group_id)[0].lifecycle(),
            PeerChannelLifecycle::Closed
        );
        assert!(restored.peer_channels(&group_id)[0].readiness().is_empty());
    }

    /// A channel becomes Ready only after both logical Local EAIOS endpoints identify one instance.
    #[test]
    fn peer_channel_requires_two_ended_identified_readiness() {
        let context_id = CoordinationContextId::new("guidance").expect("context id valid");
        let context = CoordinationContext::new_with_coordination(
            context_id.clone(),
            vec![
                ContextRole::new(
                    ContextRoleId::new("dog").expect("role id valid"),
                    ActorId::new("dog").expect("actor id valid"),
                ),
                ContextRole::new(
                    ContextRoleId::new("cane").expect("role id valid"),
                    ActorId::new("cane").expect("actor id valid"),
                ),
            ],
            vec![
                ExecutionRelationSpec::new(
                    domain::ExecutionRelationId::new("relation").expect("relation id valid"),
                    domain::PlannedExecutionRef::new(
                        domain::TaskId::new("dog-task").expect("task id valid"),
                        domain::RoleId::new("dog-role").expect("role id valid"),
                    ),
                    domain::PlannedExecutionRef::new(
                        domain::TaskId::new("cane-task").expect("task id valid"),
                        domain::RoleId::new("cane-role").expect("role id valid"),
                    ),
                    domain::ExecutionRelationKind::RequiresActive,
                )
                .expect("relation valid"),
            ],
            ExecutionCouplingMode::TightlyCoupledCooperation,
            Some(
                GroupSharedViewSpec::new(
                    None,
                    vec![domain::GroupViewBinding::new_execution(
                        ContextRoleId::new("dog").expect("role id valid"),
                    )],
                    true,
                )
                .expect("view valid"),
            ),
            Some(PeerChannelSpec {
                profile_id: "guidance-peer".to_string(),
                message_schema: "guidance/v1".to_string(),
            }),
        )
        .expect("context valid");
        let group_id = ExecutionGroupId::new("group-guidance").expect("group id valid");
        let mut runtime = RuntimeExecutionManager::new();
        runtime
            .register_coordination_context(&group_id, &context)
            .expect("context registers");
        let readiness = |role: &str, node: &str, instance: &str, sequence: u64, ready: bool| {
            PeerChannelReadinessEvidence {
                group_id: group_id.clone(),
                context_id: context_id.clone(),
                context_role_id: ContextRoleId::new(role).expect("role id valid"),
                node_id: NodeId::new(node).expect("node id valid"),
                local_system_id: LocalSystemId::new(format!("{role}-system"))
                    .expect("local system id valid"),
                session_id: format!("session-{node}"),
                channel_instance_id: instance.to_string(),
                profile_id: "guidance-peer".to_string(),
                message_schema: "guidance/v1".to_string(),
                sequence,
                received_at: TimestampMs::new(sequence),
                expires_at: TimestampMs::new(sequence + 100),
                ready,
            }
        };
        runtime
            .observe_peer_channel_readiness(readiness("dog", "dog-a", "channel-1", 1, true))
            .expect("first endpoint confirms");
        assert_eq!(
            runtime.coordination_readiness(&group_id, &context_id),
            Some(CoordinationReadiness::WaitingForPeerChannel)
        );
        runtime
            .observe_peer_channel_readiness(readiness("cane", "cane-a", "channel-1", 1, true))
            .expect("second endpoint confirms");
        assert_eq!(
            runtime.peer_channels(&group_id)[0].lifecycle(),
            PeerChannelLifecycle::Ready
        );
        let mut wrong_profile = readiness("cane", "cane-a", "channel-1", 2, true);
        wrong_profile.profile_id = "different-profile".to_string();
        runtime
            .observe_peer_channel_readiness(wrong_profile)
            .expect("descriptor conflict becomes a channel fence");
        runtime
            .observe_peer_channel_readiness(readiness("dog", "dog-a", "channel-1", 2, true))
            .expect("unaffected endpoint renews");
        assert_eq!(
            runtime.peer_channels(&group_id)[0].lifecycle(),
            PeerChannelLifecycle::Fenced
        );
        runtime
            .observe_peer_channel_readiness(readiness("cane", "cane-a", "channel-1", 3, true))
            .expect("conflicting endpoint reproves the declared descriptor");
        assert_eq!(
            runtime.peer_channels(&group_id)[0].lifecycle(),
            PeerChannelLifecycle::Ready
        );
        runtime.fence_peer_channels_for_node(&NodeId::new("dog-a").expect("node id valid"));
        assert_eq!(
            runtime.peer_channels(&group_id)[0].lifecycle(),
            PeerChannelLifecycle::Fenced
        );
        runtime
            .observe_peer_channel_readiness(readiness("cane", "cane-a", "channel-1", 4, true))
            .expect("connected endpoint renews");
        assert_eq!(
            runtime.peer_channels(&group_id)[0].lifecycle(),
            PeerChannelLifecycle::Fenced
        );
        runtime
            .observe_peer_channel_readiness(readiness("dog", "dog-a", "channel-1", 4, true))
            .expect("lost endpoint confirms through a new route");
        assert_eq!(
            runtime.peer_channels(&group_id)[0].lifecycle(),
            PeerChannelLifecycle::Ready
        );
        runtime.refresh_peer_channel_deadlines(TimestampMs::new(104));
        assert_eq!(
            runtime.peer_channels(&group_id)[0].lifecycle(),
            PeerChannelLifecycle::Fenced
        );
        runtime
            .observe_peer_channel_readiness(readiness("dog", "dog-a", "channel-1", 104, true))
            .expect("first endpoint renews");
        runtime
            .observe_peer_channel_readiness(readiness("cane", "cane-a", "channel-1", 104, true))
            .expect("second endpoint renews");
        assert_eq!(
            runtime.peer_channels(&group_id)[0].lifecycle(),
            PeerChannelLifecycle::Ready
        );
        runtime
            .observe_peer_channel_readiness(readiness("cane", "cane-a", "channel-2", 105, true))
            .expect("new instance is retained as a conflict fence");
        assert_eq!(
            runtime.peer_channels(&group_id)[0].lifecycle(),
            PeerChannelLifecycle::Fenced
        );
    }
}
