[package]
name = "control"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
domain = { path = "../domain" }
ports = { path = "../ports" }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
state = { path = "../state" }
serde_json = "1.0"
