//! Whole-Group continuation through actual scheduling, ownership, HTTP and durable application ticks.

use super::*;
use domain::{ExecutionGroupId, NodeId, TimestampMs};
use integration::grpc::v0_4::{ExecutionPhase, NodeMessage, node_message::Message as NodePayload};
use orchestration::RemoteExecutionStatus;

#[path = "group_recovery_transport.rs"]
mod transport;

/// Declares original owner support, session transport and one exclusive operation resource.
fn registration(index: usize, supported: bool, capacity: u32) -> domain::NodeRegistration {
    let owner = domain::LocalSystemId::new("worker-runtime").unwrap();
    let operation = domain::OperationRef::new("compute", "work", "v1").unwrap();
    let metadata = BTreeMap::from([
        (
            integration::EXECUTION_SESSION_METADATA_KEY.into(),
            integration::EXECUTION_SESSION_METADATA_VALUE.into(),
        ),
        (
            domain::EXECUTION_RECOVERY_METADATA_KEY.into(),
            serde_json::json!({
                "schema_version": domain::EXECUTION_RECOVERY_PROFILE_SCHEMA,
                "operations": [{"operation": operation, "stop_scope": "execution-group",
                    "continuation": if supported {"repeat-after-stop"} else {"unsupported"}}]
            })
            .to_string(),
        ),
    ]);
    let resource = domain::Resource::new(
        domain::ResourceId::new(format!("cpu-{index}")).unwrap(),
        domain::ResourceKind::Compute,
        capacity,
    )
    .unwrap();
    domain::NodeRegistration::new_with_local_systems(
        NodeId::new(format!("node-{index}")).unwrap(),
        vec![domain::LocalSystemDescriptor::new(
            owner.clone(),
            domain::LocalRuntime::new("fixture", "1").unwrap(),
            metadata,
        )],
        domain::NodeContractVersion::v0_6(),
        vec![domain::Capability::new(
            domain::CapabilityKind::Compute,
            true,
        )],
        BTreeMap::from([(operation.as_legacy_contract().clone(), owner.clone())]),
        Vec::new(),
        vec![resource.clone()],
        BTreeMap::from([(resource.id().clone(), owner.clone())]),
    )
    .unwrap()
    .with_operation_support(vec![domain::OperationSupport::new(operation, owner)])
    .unwrap()
}

/// Creates a general independent Mission, not an Episode51 plan or an inferred distinctness rule.
fn plan(count: usize, verifier: bool) -> domain::MissionPlan {
    independent_plan(count, verifier, false)
}

/// Varies logical topology while retaining the same canonical capabilities and resource contract.
fn independent_plan(count: usize, verifier: bool, sequential: bool) -> domain::MissionPlan {
    let operation = serde_json::json!({"namespace":"compute", "name":"work", "version":"v1"});
    let tasks: Vec<_> = (0..count).map(|index| serde_json::json!({
        "id":format!("task-{index}"), "description":"independent work", "depends_on":if sequential && index>0 {vec![format!("task-{}",index-1)]} else {Vec::new()},
        "context_id":"context", "coupling_mode":"independent",
        "timing":{"earliest_start_offset_ms":0, "latest_start_offset_ms":null, "completion_deadline_offset_ms":null},
        "satisfaction":{"expected_effect":"work complete", "basis":if verifier {"verifier-evidence"} else {"execution-report"},
            "verifier":if verifier {serde_json::json!({"contract":{"namespace":"observation","name":"verify","version":"v1"},"predicate":"joint goal","max_evidence_age_ms":5000})} else {serde_json::Value::Null}},
        "roles":[{"id":"worker","context_role":format!("participant-{index}"),"resource_scope":"task",
            "requirements":{"capabilities":[{"contract":operation,"constraints":[]}],"resources":[{"kind":"compute","units":2}]},
            "execution_intent":{"operation":operation,"objective":"independent work","parameters":{}}}]
    })).collect();
    decode_mission_plan(&serde_json::json!({
        "schema_version":"roboguide.mission-plan/v0.8",
        "mission":{"id":"group-mission","objective":"independent work","actors":(0..if sequential {1} else {count}).map(|index|serde_json::json!({"id":format!("actor-{index}")})).collect::<Vec<_>>()},
        "contexts":[{"id":"context","roles":(0..count).map(|index|serde_json::json!({"id":format!("participant-{index}"),"actor":format!("actor-{}",if sequential {0} else {index})})).collect::<Vec<_>>(),
            "relations":[],"coupling_mode":"independent","executor_constraints":[]}], "tasks":tasks
    }).to_string()).unwrap()
}

/// Owns real application state and the original attempts generated by Control.
struct Fixture {
    /// Keeps the database and run-local evidence separate from all user files.
    directory: tempfile::TempDir,
    /// Real Controller authority, used in HTTP and candidate/checkpoint transitions.
    controller: Arc<Mutex<ControllerState>>,
    /// Real durable event and checkpoint store.
    events: state::SqliteEventLog,
    /// Original physical attempts, preserved across continuation.
    originals: Vec<runtime::ExecutionAttemptSnapshot>,
    /// Exact Group scope selected during actual Mission submission.
    group_id: ExecutionGroupId,
    /// Stable evidence correlation.
    correlation: domain::CorrelationId,
}

impl Fixture {
    /// Runs real Submit -> Match -> Schedule -> Commit -> Bind with no Node/model/Habitat process.
    fn new(count: usize, supported: bool, verifier: bool) -> Self {
        Self::with_router(
            count,
            supported,
            verifier,
            integration::GrpcNodeRouter::default(),
        )
    }

    /// Supplies an actual formal command router without replacing any authority or transition.
    fn with_router(
        count: usize,
        supported: bool,
        verifier: bool,
        router: integration::GrpcNodeRouter,
    ) -> Self {
        Self::with_plan(count, supported, plan(count, verifier), router)
    }

    /// Keeps real Control decisions while changing the accepted logical topology under test.
    fn with_plan(
        count: usize,
        supported: bool,
        plan: domain::MissionPlan,
        router: integration::GrpcNodeRouter,
    ) -> Self {
        let directory = tempfile::tempdir().unwrap();
        let events = state::SqliteEventLog::open(directory.path().join("events.sqlite3")).unwrap();
        let correlation = domain::CorrelationId::new("group-test").unwrap();
        let group_id = ExecutionGroupId::new("group-test").unwrap();
        let mut control = control::ControlPlane::new();
        let mut state = state::InMemorySharedNodeState::new();
        for index in 0..count {
            control
                .register_node(
                    &mut state,
                    registration(index, supported, 2),
                    domain::NodeStatus::new(domain::NodeHealth::Online, TimestampMs::new(1)),
                    TimestampMs::new(1),
                    &correlation,
                    &mut events.clone(),
                )
                .unwrap();
        }
        control
            .install_physical_entity_registry(
                domain::PhysicalEntityRegistrySnapshot::new(
                    domain::PhysicalEntityRegistryId::new("test-deployment").unwrap(),
                    1,
                    domain::PhysicalEntityRoutingProfile::OneRoutableEntityPerNode,
                    (0..count)
                        .map(|index| {
                            domain::PhysicalEntityRegistration::new(
                                domain::PhysicalEntityId::new(format!("entity-{index}")).unwrap(),
                                NodeId::new(format!("node-{index}")).unwrap(),
                            )
                        })
                        .collect(),
                )
                .unwrap(),
            )
            .unwrap();
        let mut orchestrator = MissionOrchestrator::new();
        orchestrator
            .submit(
                plan,
                group_id.clone(),
                &mut control,
                TimestampMs::new(2),
                &correlation,
                &mut events.clone(),
            )
            .unwrap();
        let mut controller = ControllerState {
            bridge: IntegrationRuntimeBridge::new(control, state, events.clone(), router),
            orchestrator,
            mission_admissions: BTreeMap::new(),
            verifier_seen: BTreeSet::new(),
            verifier_source_digest: None,
        };
        drive_ready_tasks(
            &mut controller,
            TimestampMs::new(3),
            &correlation,
            &mut events.clone(),
        )
        .unwrap();
        let originals = controller.bridge.attempt_history();
        assert_eq!(originals.len(), count);
        assert!(
            originals
                .iter()
                .all(|attempt| attempt.command().session().is_some())
        );
        let fixture = Self {
            directory,
            controller: Arc::new(Mutex::new(controller)),
            events,
            originals,
            group_id,
            correlation,
        };
        for attempt in &fixture.originals {
            fixture.fact(attempt, 1, ExecutionPhase::Started, 4);
        }
        fixture
    }

    /// Injects a real ordered owner fact through the Node Protocol reducer and lifecycle handler.
    fn fact(
        &self,
        attempt: &runtime::ExecutionAttemptSnapshot,
        sequence: u64,
        phase: ExecutionPhase,
        received: u64,
    ) {
        let mut controller = self.controller.lock().unwrap();
        controller
            .bridge
            .consume(
                integration::GrpcNodeEvent::NodeMessage {
                    node_id: attempt.command().node_id().to_string(),
                    session_id: "test-session".into(),
                    message: NodeMessage {
                        message: Some(NodePayload::ExecutionSnapshot(
                            integration::grpc::v0_4::ExecutionSnapshot {
                                session_id: "test-session".into(),
                                execution_id: attempt.execution_id().into(),
                                last_sequence: sequence,
                                phase: phase as i32,
                                reason: "actual observed local outcome".into(),
                            },
                        )),
                    },
                },
                TimestampMs::new(received),
                &self.correlation,
            )
            .unwrap();
        apply_runtime_events(
            &mut controller,
            TimestampMs::new(received),
            &self.correlation,
            &mut self.events.clone(),
        )
        .unwrap();
    }

    /// Admits a complete original set with separate explicit permission for every invocation.
    fn authorize(&self) {
        self.authorize_at(5);
    }

    /// Freezes a supplied receive-time origin for immutable continuation-budget tests.
    fn authorize_at(&self, now: u64) {
        let members = self
            .originals
            .iter()
            .map(|attempt| runtime::GroupRecoveryMember {
                execution_id: attempt.execution_id().into(),
                expected_node_id: attempt.command().node_id().clone(),
                repeat_authorized: true,
            })
            .collect();
        self.controller
            .lock()
            .unwrap()
            .bridge
            .request_group_recovery(
                &self.group_id,
                "round-1",
                members,
                TimestampMs::new(now),
                100,
                2,
            )
            .unwrap();
    }

    /// Drives the actual transactional timer and its existing command outbox after durable commit.
    fn tick(&self, now: u64) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        drive_application_timer(
            &self.controller,
            &self.events,
            &Arc::new(Mutex::new(())),
            TimestampMs::new(now),
            None,
        )
    }

    /// Reads exact resource ownership, never an Allocation projection or Node-local lock.
    fn reservations(&self) -> serde_json::Value {
        serde_json::to_value(
            self.controller
                .lock()
                .unwrap()
                .bridge
                .control()
                .checkpoint(),
        )
        .unwrap()["reservations"]
            .clone()
    }

    /// Updates the actual registration while preserving the Node and resource identity.
    fn update(&self, index: usize, supported: bool, capacity: u32) {
        let mut controller = self.controller.lock().unwrap();
        let mut state = controller.bridge.state().clone();
        controller
            .bridge
            .control_mut()
            .register_node(
                &mut state,
                registration(index, supported, capacity),
                domain::NodeStatus::new(domain::NodeHealth::Online, TimestampMs::new(15)),
                TimestampMs::new(15),
                &self.correlation,
                &mut self.events.clone(),
            )
            .unwrap();
        *controller.bridge.state_mut() = state;
    }

    /// Builds the unchanged wire authorization for HTTP parse/admission checks.
    fn command(&self) -> serde_json::Value {
        serde_json::json!({"schema_version":"roboguide.group-recovery-command/v0.1", "recovery_id":"round-1",
            "members":self.originals.iter().map(|attempt|serde_json::json!({"execution_id":attempt.execution_id(),"expected_node_id":attempt.command().node_id(),"repeat_authorized":true})).collect::<Vec<_>>(),
            "timeout_ms":100,"max_replacements":2})
    }

    /// Uses the real loopback HTTP handler with the same explicit virtual time domain as Node facts.
    async fn request(
        &self,
        method: &str,
        path: &str,
        body: serde_json::Value,
        now: u64,
    ) -> (String, serde_json::Value) {
        use tokio::io::{AsyncReadExt, AsyncWriteExt};
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let address = listener.local_addr().unwrap();
        let clock = runtime::FixedClock::new(TimestampMs::new(now));
        let gate = Arc::new(Mutex::new(()));
        let server = async {
            let (mut stream, _) = listener.accept().await.unwrap();
            handle_http_connection(
                &mut stream,
                &self.controller,
                &self.events,
                &gate,
                &clock,
                None,
                None,
            )
            .await
            .unwrap();
        };
        let client = async {
            let mut stream = tokio::net::TcpStream::connect(address).await.unwrap();
            let bytes = serde_json::to_vec(&body).unwrap();
            let header = format!(
                "{method} {path} HTTP/1.1\r\nHost:localhost\r\nContent-Length:{}\r\n\r\n",
                bytes.len()
            );
            stream.write_all(header.as_bytes()).await.unwrap();
            stream.write_all(&bytes).await.unwrap();
            let mut response = String::new();
            stream.read_to_string(&mut response).await.unwrap();
            let (headers, json) = response.split_once("\r\n\r\n").unwrap();
            (
                headers.lines().next().unwrap().to_string(),
                serde_json::from_str(json).unwrap(),
            )
        };
        tokio::time::timeout(Duration::from_secs(5), async {
            tokio::join!(server, client).1
        })
        .await
        .unwrap()
    }
}

/// Three independent Tasks retain every original reservation until the complete real stop barrier.
#[test]
fn full_group_stop_prepares_all_new_attempts_without_partial_release() {
    let fixture = Fixture::new(3, true, false);
    let original = fixture.reservations();
    fixture.authorize();
    fixture.fact(&fixture.originals[0], 2, ExecutionPhase::Cancelled, 20);
    fixture.fact(&fixture.originals[1], 2, ExecutionPhase::Cancelled, 21);
    fixture.tick(22).unwrap();
    assert_eq!(
        fixture
            .controller
            .lock()
            .unwrap()
            .bridge
            .attempt_history()
            .len(),
        3
    );
    assert_eq!(fixture.reservations(), original);
    fixture.fact(&fixture.originals[2], 2, ExecutionPhase::Cancelled, 23);
    fixture.tick(24).unwrap();
    let replacements: Vec<_> = fixture
        .controller
        .lock()
        .unwrap()
        .bridge
        .attempt_history()
        .into_iter()
        .filter(|attempt| {
            !fixture
                .originals
                .iter()
                .any(|old| old.execution_id() == attempt.execution_id())
        })
        .collect();
    assert_eq!(replacements.len(), 3);
    assert_eq!(fixture.reservations(), original);
    for fresh in &replacements {
        let old = fixture
            .originals
            .iter()
            .find(|old| old.command().task_ref() == fresh.command().task_ref())
            .unwrap();
        assert_eq!(fresh.command().node_id(), old.command().node_id());
        assert_eq!(fresh.command().intent(), old.command().intent());
        assert_eq!(fresh.command().session(), old.command().session());
        fixture.fact(fresh, 1, ExecutionPhase::Started, 25);
        fixture.fact(fresh, 2, ExecutionPhase::Completed, 26);
    }
    fixture.tick(27).unwrap();
    assert!(fixture.reservations().as_object().unwrap().is_empty());
    assert_eq!(
        fixture
            .controller
            .lock()
            .unwrap()
            .orchestrator
            .execution(&domain::MissionId::new("group-mission").unwrap())
            .unwrap()
            .lifecycle(),
        orchestration::MissionExecutionLifecycle::Completed
    );
    assert!(fixture.originals.iter().all(|old| {
        fixture
            .controller
            .lock()
            .unwrap()
            .bridge
            .execution_status(old.execution_id())
            == Some(RemoteExecutionStatus::Cancelled)
    }));
}

/// A Completed verifier-backed peer is preserved; local retry cannot fabricate semantic satisfaction.
#[test]
fn completed_peer_is_not_repeated_and_missing_verifier_keeps_mission_running() {
    let fixture = Fixture::new(2, true, true);
    fixture.fact(&fixture.originals[0], 2, ExecutionPhase::Completed, 5);
    fixture.tick(6).unwrap();
    fixture.authorize_at(7);
    let original = fixture.reservations();
    fixture.fact(&fixture.originals[1], 2, ExecutionPhase::Cancelled, 20);
    fixture.tick(21).unwrap();
    let controller = fixture.controller.lock().unwrap();
    assert_eq!(controller.bridge.attempt_history().len(), 3);
    assert_eq!(
        controller
            .bridge
            .group_recovery(&fixture.group_id)
            .unwrap()
            .replacements
            .len(),
        1
    );
    assert_eq!(
        controller
            .bridge
            .execution_status(fixture.originals[0].execution_id()),
        Some(RemoteExecutionStatus::Completed)
    );
    assert_eq!(
        controller
            .orchestrator
            .execution(&domain::MissionId::new("group-mission").unwrap())
            .unwrap()
            .lifecycle(),
        orchestration::MissionExecutionLifecycle::Running
    );
    drop(controller);
    assert_eq!(fixture.reservations(), original);
}

/// Support or physical resource changes remain observable deferrals, not partial or fake recovery.
#[test]
fn changed_support_or_capacity_prevents_continuation_commit() {
    for (supported, capacity) in [(false, 2), (true, 1)] {
        let fixture = Fixture::new(2, true, false);
        fixture.authorize();
        for attempt in &fixture.originals {
            fixture.fact(attempt, 2, ExecutionPhase::Cancelled, 20);
        }
        let original = fixture.reservations();
        fixture.update(0, supported, capacity);
        fixture.tick(21).unwrap();
        let controller = fixture.controller.lock().unwrap();
        assert_eq!(controller.bridge.attempt_history().len(), 2);
        assert!(
            controller
                .bridge
                .group_continuation_blocker(&fixture.group_id, TimestampMs::new(22))
                .is_some()
        );
        drop(controller);
        assert_eq!(fixture.reservations(), original);
    }
}

/// Late or missing physical stop never renews the request or frees exclusive resources.
#[test]
fn expired_group_recovery_retains_ownership_and_fences_new_attempts() {
    let fixture = Fixture::new(2, true, false);
    fixture.authorize();
    let original = fixture.reservations();
    fixture.fact(&fixture.originals[0], 2, ExecutionPhase::Cancelled, 20);
    fixture.tick(105).unwrap();
    assert_eq!(
        fixture
            .controller
            .lock()
            .unwrap()
            .bridge
            .group_recovery_disposition(&fixture.group_id, TimestampMs::new(105)),
        runtime::GroupRecoveryDisposition::BudgetExpired
    );
    fixture.fact(&fixture.originals[1], 2, ExecutionPhase::Cancelled, 106);
    fixture.tick(107).unwrap();
    assert_eq!(
        fixture
            .controller
            .lock()
            .unwrap()
            .bridge
            .attempt_history()
            .len(),
        2
    );
    assert_eq!(fixture.reservations(), original);
}

/// Checkpoint failure rolls back fresh attempts/events; no candidate outbox reaches a Node.
#[test]
fn checkpoint_failure_rolls_back_whole_group_preparation() {
    let fixture = Fixture::new(2, true, false);
    fixture.authorize();
    for attempt in &fixture.originals {
        fixture.fact(attempt, 2, ExecutionPhase::Cancelled, 20);
    }
    let original = server_checkpoint_json(&fixture.controller.lock().unwrap()).unwrap();
    let sequence = fixture.events.latest_sequence().unwrap();
    let db = rusqlite::Connection::open(fixture.directory.path().join("events.sqlite3")).unwrap();
    let table: String = db
        .query_row(
            "SELECT name FROM sqlite_master WHERE type='table' AND name LIKE '%checkpoint%'",
            [],
            |row| row.get(0),
        )
        .unwrap();
    db.execute_batch(&format!("CREATE TRIGGER fail_checkpoint BEFORE INSERT ON {table} BEGIN SELECT RAISE(FAIL,'test checkpoint failure'); END;")).unwrap();
    assert!(fixture.tick(21).is_err());
    assert_eq!(
        server_checkpoint_json(&fixture.controller.lock().unwrap()).unwrap(),
        original
    );
    assert_eq!(fixture.events.latest_sequence().unwrap(), sequence);
    db.execute_batch("DROP TRIGGER fail_checkpoint").unwrap();
    fixture.tick(22).unwrap();
    assert_eq!(
        fixture
            .controller
            .lock()
            .unwrap()
            .bridge
            .attempt_history()
            .len(),
        4
    );
}

/// Real HTTP admits the closed Group command, rejects malformed authorization and preserves budgets.
#[tokio::test]
async fn group_http_contract_is_atomic_idempotent_and_separate_from_role_recovery() {
    let fixture = Fixture::new(2, true, false);
    let path = format!("/v1/groups/{}/recover", fixture.group_id);
    let baseline = server_checkpoint_json(&fixture.controller.lock().unwrap()).unwrap();
    for (method, malformed) in [
        ("GET", "/v1/groups//recovery"),
        ("POST", "/v1/groups//recover"),
    ] {
        let (status, _) = fixture
            .request(method, malformed, fixture.command(), 5)
            .await;
        assert!(status.contains("400"));
        assert_eq!(
            server_checkpoint_json(&fixture.controller.lock().unwrap()).unwrap(),
            baseline
        );
    }
    for variant in 0..4 {
        let mut body = fixture.command();
        match variant {
            0 => {
                body["schema_version"] = serde_json::json!("wrong");
            }
            1 => {
                body["members"][0]["repeat_authorized"] = serde_json::json!(false);
            }
            2 => {
                body["members"].as_array_mut().unwrap().pop();
            }
            _ => {
                body["members"][0]["expected_node_id"] = serde_json::json!("wrong");
            }
        }
        let (status, _) = fixture.request("POST", &path, body, 5).await;
        assert!(status.contains(if variant == 0 { "400" } else { "409" }));
        assert_eq!(
            server_checkpoint_json(&fixture.controller.lock().unwrap()).unwrap(),
            baseline
        );
    }
    let (status, result) = fixture.request("POST", &path, fixture.command(), 5).await;
    assert!(status.contains("202"));
    assert_eq!(result["command_receipt_is_stop_proof"], false);
    let (status, repeated) = fixture.request("POST", &path, fixture.command(), 25).await;
    assert!(status.contains("202"));
    assert_eq!(repeated["stop_intent"]["deadline_ms"], 105);
    for attempt in &fixture.originals {
        fixture.fact(attempt, 2, ExecutionPhase::Cancelled, 30);
    }
    fixture.tick(31).unwrap();
    let (status, view) = fixture
        .request(
            "GET",
            &format!("/v1/groups/{}/recovery", fixture.group_id),
            serde_json::Value::Null,
            32,
        )
        .await;
    assert!(status.contains("200"));
    assert_eq!(view["disposition"], "ContinuationPrepared");
    assert_eq!(
        view["stop_intent"]["replacements"]
            .as_object()
            .unwrap()
            .len(),
        2
    );
    assert_eq!(view["resources_released_by_recovery"], false);
}

/// The default unsupported deployment is refused before any durable purpose, Cancel or resource write.
#[tokio::test]
async fn default_off_group_continuation_is_rejected_before_cancel() {
    let fixture = Fixture::new(2, false, false);
    let baseline = server_checkpoint_json(&fixture.controller.lock().unwrap()).unwrap();
    let (status, _) = fixture
        .request(
            "POST",
            &format!("/v1/groups/{}/recover", fixture.group_id),
            fixture.command(),
            5,
        )
        .await;
    assert!(status.contains("409"));
    assert_eq!(
        server_checkpoint_json(&fixture.controller.lock().unwrap()).unwrap(),
        baseline
    );
}

/// A new Group permission cannot be smuggled into v17; genuine old checkpoints have none.
#[test]
fn versioned_restore_rejects_group_authorization_in_old_checkpoint_schema() {
    let fixture = Fixture::new(2, true, false);
    fixture.authorize();
    let mut checkpoint: serde_json::Value = serde_json::from_str(
        &fixture
            .controller
            .lock()
            .unwrap()
            .bridge
            .checkpoint_json()
            .unwrap(),
    )
    .unwrap();
    checkpoint["schema"] = serde_json::json!("roboguide.controller-checkpoint/v17");
    assert!(
        IntegrationRuntimeBridge::restore_from_checkpoint(
            &checkpoint.to_string(),
            fixture.events.clone(),
            integration::GrpcNodeRouter::default(),
            TimestampMs::new(20)
        )
        .is_err()
    );
    checkpoint["runtime"]["group_recoveries"] = serde_json::json!([]);
    let restored = IntegrationRuntimeBridge::restore_from_checkpoint(
        &checkpoint.to_string(),
        fixture.events.clone(),
        integration::GrpcNodeRouter::default(),
        TimestampMs::new(20),
    )
    .unwrap();
    assert!(restored.group_recovery(&fixture.group_id).is_none());
}

/// Proposal is non-authoritative and Commit independently rechecks changed live capacity.
#[test]
fn retained_control_commit_rechecks_state_after_proposal_without_releasing_resources() {
    let fixture = Fixture::new(2, true, false);
    fixture.authorize();
    for attempt in &fixture.originals {
        fixture.fact(attempt, 2, ExecutionPhase::Cancelled, 20);
    }
    let ownership = fixture.reservations();
    let proposal = {
        let live = fixture.controller.lock().unwrap();
        live.bridge
            .control()
            .propose_group_continuation(
                live.bridge.state(),
                &fixture.group_id,
                "round-1",
                fixture
                    .originals
                    .iter()
                    .map(|attempt| attempt.command().clone())
                    .collect(),
                TimestampMs::new(21),
                &fixture.correlation,
                &mut fixture.events.clone(),
            )
            .unwrap()
    };
    assert_eq!(fixture.reservations(), ownership);
    fixture.update(0, true, 1);
    let sequence = fixture.events.latest_sequence().unwrap();
    let mut live = fixture.controller.lock().unwrap();
    let current = live.bridge.state().clone();
    assert!(
        live.bridge
            .control_mut()
            .commit_group_continuation(
                &current,
                &proposal,
                TimestampMs::new(22),
                &fixture.correlation,
                &mut fixture.events.clone()
            )
            .is_err()
    );
    drop(live);
    assert_eq!(fixture.events.latest_sequence().unwrap(), sequence);
    assert_eq!(fixture.reservations(), ownership);
}

/// Ordinary Mission cancellation overrides a pending or already prepared complete recovery round.
#[tokio::test]
async fn mission_cancel_aborts_group_round_and_waits_for_all_actual_attempts_to_stop() {
    for prepared in [false, true] {
        let fixture = Fixture::new(2, true, false);
        fixture.authorize();
        let ownership = fixture.reservations();
        if prepared {
            for attempt in &fixture.originals {
                fixture.fact(attempt, 2, ExecutionPhase::Cancelled, 20);
            }
            fixture.tick(21).unwrap();
        }
        let (status, _) = fixture
            .request(
                "POST",
                "/v1/missions/group-mission/cancel",
                serde_json::json!({}),
                22,
            )
            .await;
        assert!(status.contains("202"));
        let attempts = {
            let live = fixture.controller.lock().unwrap();
            assert_eq!(
                live.bridge
                    .group_recovery_disposition(&fixture.group_id, TimestampMs::new(23)),
                runtime::GroupRecoveryDisposition::Aborted
            );
            assert_eq!(
                live.orchestrator
                    .execution(&domain::MissionId::new("group-mission").unwrap())
                    .unwrap()
                    .lifecycle(),
                orchestration::MissionExecutionLifecycle::Cancelling
            );
            live.bridge
                .attempt_history()
                .into_iter()
                .filter(|attempt| !attempt.status().is_terminal())
                .collect::<Vec<_>>()
        };
        assert_eq!(fixture.reservations(), ownership);
        for attempt in &attempts {
            fixture.fact(attempt, 2, ExecutionPhase::Cancelled, 24);
        }
        fixture.tick(25).unwrap();
        assert_eq!(
            fixture
                .controller
                .lock()
                .unwrap()
                .orchestrator
                .execution(&domain::MissionId::new("group-mission").unwrap())
                .unwrap()
                .lifecycle(),
            orchestration::MissionExecutionLifecycle::Cancelled
        );
        assert_eq!(fixture.reservations(), serde_json::json!({}));
        assert_eq!(
            fixture
                .controller
                .lock()
                .unwrap()
                .bridge
                .attempt_history()
                .len(),
            if prepared { 4 } else { 2 }
        );
    }
}

/// Restart preserves the original whole-set deadline, facts and reservations; no replay is automatic.
#[test]
fn controller_restore_keeps_group_budget_and_requires_missing_owner_fact() {
    let fixture = Fixture::new(2, true, false);
    fixture.authorize();
    fixture.fact(&fixture.originals[0], 2, ExecutionPhase::Cancelled, 20);
    let ownership = fixture.reservations();
    let checkpoint = fixture
        .controller
        .lock()
        .unwrap()
        .bridge
        .checkpoint_json()
        .unwrap();
    let mut restored = IntegrationRuntimeBridge::restore_from_checkpoint(
        &checkpoint,
        fixture.events.clone(),
        integration::GrpcNodeRouter::default(),
        TimestampMs::new(30),
    )
    .unwrap();
    assert_eq!(
        restored
            .group_recovery(&fixture.group_id)
            .unwrap()
            .deadline_ms,
        105
    );
    assert_eq!(
        restored
            .group_recovery(&fixture.group_id)
            .unwrap()
            .confirmed_at_ms[fixture.originals[0].execution_id()],
        20
    );
    assert_eq!(
        restored.execution_status(fixture.originals[1].execution_id()),
        Some(RemoteExecutionStatus::Unknown)
    );
    assert_eq!(
        restored
            .flush_command_outboxes_at(TimestampMs::new(31))
            .unwrap_or(0),
        0
    );
    assert!(
        !restored
            .prepare_group_continuation(
                &fixture.group_id,
                TimestampMs::new(32),
                &fixture.correlation
            )
            .unwrap()
    );
    assert_eq!(
        serde_json::to_value(restored.control().checkpoint()).unwrap()["reservations"],
        ownership
    );
    assert_eq!(
        restored.group_recovery_disposition(&fixture.group_id, TimestampMs::new(105)),
        runtime::GroupRecoveryDisposition::BudgetExpired
    );
}

/// Recovery repeats the active Task once; the same Actor advances normally only after its release.
#[test]
fn single_actor_sequential_tasks_resume_same_slot_before_dispatching_the_next_task() {
    let fixture = Fixture::with_plan(
        1,
        true,
        independent_plan(2, false, true),
        integration::GrpcNodeRouter::default(),
    );
    fixture.authorize();
    fixture.tick(10).unwrap();
    assert_eq!(
        fixture
            .controller
            .lock()
            .unwrap()
            .bridge
            .attempt_history()
            .len(),
        1
    );
    fixture.fact(&fixture.originals[0], 2, ExecutionPhase::Cancelled, 20);
    fixture.tick(21).unwrap();
    let retry = fixture
        .controller
        .lock()
        .unwrap()
        .bridge
        .attempt_history()
        .into_iter()
        .find(|attempt| attempt.execution_id() != fixture.originals[0].execution_id())
        .unwrap();
    assert_eq!(retry.command().task_id().as_str(), "task-0");
    assert_eq!(
        retry.command().node_id(),
        fixture.originals[0].command().node_id()
    );
    fixture.fact(&retry, 1, ExecutionPhase::Started, 22);
    fixture.fact(&retry, 2, ExecutionPhase::Completed, 23);
    fixture.tick(24).unwrap();
    let next = fixture
        .controller
        .lock()
        .unwrap()
        .bridge
        .attempt_history()
        .into_iter()
        .find(|attempt| attempt.command().task_id().as_str() == "task-1")
        .unwrap();
    assert_eq!(next.command().node_id(), retry.command().node_id());
    assert_eq!(next.command().session(), retry.command().session());
    fixture.fact(&next, 1, ExecutionPhase::Started, 25);
    fixture.fact(&next, 2, ExecutionPhase::Completed, 26);
    fixture.tick(27).unwrap();
    assert_eq!(
        fixture
            .controller
            .lock()
            .unwrap()
            .orchestrator
            .execution(&domain::MissionId::new("group-mission").unwrap())
            .unwrap()
            .lifecycle(),
        orchestration::MissionExecutionLifecycle::Completed
    );
    assert_eq!(
        fixture
            .controller
            .lock()
            .unwrap()
            .bridge
            .attempt_history()
            .len(),
        3
    );
}

/// Current registration cannot remove immutable-session transport while retaining recovery metadata.
#[tokio::test]
async fn missing_current_session_transport_rejects_group_stop_before_cancel() {
    let fixture = Fixture::new(2, true, false);
    let mut declaration = serde_json::to_value(registration(0, true, 2)).unwrap();
    declaration["local_systems"][0]["metadata"]
        .as_object_mut()
        .unwrap()
        .remove(integration::EXECUTION_SESSION_METADATA_KEY);
    {
        let mut live = fixture.controller.lock().unwrap();
        let mut state = live.bridge.state().clone();
        live.bridge
            .control_mut()
            .register_node(
                &mut state,
                serde_json::from_value(declaration).unwrap(),
                domain::NodeStatus::new(domain::NodeHealth::Online, TimestampMs::new(5)),
                TimestampMs::new(5),
                &fixture.correlation,
                &mut fixture.events.clone(),
            )
            .unwrap();
        *live.bridge.state_mut() = state;
    }
    let baseline = server_checkpoint_json(&fixture.controller.lock().unwrap()).unwrap();
    let (status, _) = fixture
        .request(
            "POST",
            &format!("/v1/groups/{}/recover", fixture.group_id),
            fixture.command(),
            6,
        )
        .await;
    assert!(status.contains("409"));
    assert_eq!(
        server_checkpoint_json(&fixture.controller.lock().unwrap()).unwrap(),
        baseline
    );
}

/// A delayed Accepted snapshot retains its real timestamp and does not bypass admission expiry.
#[test]
fn late_node_admission_remains_expired_and_keeps_real_runtime_facts() {
    let fixture = Fixture::new(2, true, true);
    fixture.authorize();
    for original in &fixture.originals {
        fixture.fact(original, 2, ExecutionPhase::Cancelled, 20);
    }
    fixture.tick(21).unwrap();
    let replacements = fixture
        .controller
        .lock()
        .unwrap()
        .bridge
        .attempt_history()
        .into_iter()
        .filter(|attempt| {
            !fixture
                .originals
                .iter()
                .any(|original| original.execution_id() == attempt.execution_id())
        })
        .collect::<Vec<_>>();
    fixture.fact(&replacements[0], 1, ExecutionPhase::Accepted, 22);
    fixture.fact(&replacements[1], 1, ExecutionPhase::Accepted, 105);
    let live = fixture.controller.lock().unwrap();
    assert_eq!(
        live.bridge
            .group_recovery_disposition(&fixture.group_id, TimestampMs::new(106)),
        runtime::GroupRecoveryDisposition::BudgetExpired
    );
    assert_eq!(
        live.bridge
            .group_recovery(&fixture.group_id)
            .unwrap()
            .admitted_at_ms[replacements[1].execution_id()],
        105
    );
    assert_eq!(
        live.bridge.execution_status(replacements[1].execution_id()),
        Some(RemoteExecutionStatus::Accepted)
    );
    assert_eq!(
        live.orchestrator
            .execution(&domain::MissionId::new("group-mission").unwrap())
            .unwrap()
            .lifecycle(),
        orchestration::MissionExecutionLifecycle::Running
    );
}
